### ISSUE TITLE
[will be deleted] Proposition

### ISSUE THREAD

**Issue by David-Maran** [ochurlaud/geneamania#1]
Bonjour, j'avais proposer à l'auteur de cette application mon aide pour le développement, cette personne n'a jamais daigner me répondre et m'a même supprimer du forum. Si vous regardez le code de l'application et l'architecture du site geneamania, c'est du bricolage. Si vous souhaitez refaire un projet avec cette application comme base, je peux contribuer dans la mesure ou ce projet ne s'appel plus geneamania et n'a plus aucun rapport avec ce site.

**Comment by David-Maran** [comment]
Un exemple de ce qu'il ne faut pas faire: il a mélanger dans l'application le code pour la configuration des sites "premium" de geneamania. C'est pour cette raison que vous avez du modifier le code.

**Comment by ochurlaud** [comment]
Merci pour la proposition mais je ne compte pas forker le projet ni me lancer dans un nouveau dev. Mon objectif est juste de garder les motifs faites et de proposer plus simplement les améliorations simple que je pourrais avoir.
Et je ne juge pas le travail fait. Sans doute que j'aurais développé et architecturé autrement mais au moins Geneamania fonctionne et existe. J'ai beaucoup de respect pour cela.

**Comment by ochurlaud** [comment]
En revanche si tu souhaites participer à cette démarche tu peux proposer une pull request ici et en parler sur le forum de Jean Luc

**Comment by David-Maran** [comment]
> En revanche si tu souhaites participer à cette démarche tu peux proposer une pull request ici et en parler sur le forum de Jean Luc

Comme je l'ai signifier, déjà fais en 2021, sans réponse du créateur de l'app et viré du forum, donc non je ne collaborerais pas avec cette personne.
